### ISSUE TITLE
Enable macvlan (bis)

### ISSUE THREAD

**Issue by victornoel** [Excito/kernel-4.9#1]
Hi, we already had the discussion with the previous kernel (see https://github.com/Excito/kernel-3.18/issues/1) any way to get the modules described in this previous issue?

**Comment by victornoel** [comment]
and by the way, the latest version of the kernel you released is not available via `https//repo.excito.org stretch/main`

**Comment by victornoel** [comment]
and by the way again, note that the debian repository still show stretch as testing and not stable! not sure it is the best place to report this, but there doesn't seem to be any github project for the debian repository :)

```
# apt search bubba3-kernel
Sorting... Done
Full Text Search... Done
bubba3-kernel/testing,now 1:4.9.35-2 armel [installed]
  The linux kernel for the Excito platforms
```

**Comment by MouettE-SC** [comment]
OK I'm going to take a look on all this in the next few days.

**Comment by MouettE-SC** [comment]
The new kernel is being built on my dev b3, it should be uploaded tomorrow. I also fixed the repository configuration, we'll see when I'll put the kernel.

**Comment by MouettE-SC** [comment]
Kernel 4.9.51-1 is uploaded to the stretch repository and all the repositories configurations are fixed. Everything should be good let me know if something's missing.

**Comment by victornoel** [comment]
everything seems to be good! Thanks a lot @MouettE-SC :)
